name: .NET Build & Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check Out Code
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Restore Dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src --configuration Release --no-restore
      - name: Unit Tests
        run: |
          cd ./tests/AeroSharp.UnitTests/
          dotnet test --no-restore -nodereuse:false \
            /p:UseSharedCompilation=false \
            /p:UseRazorBuildServer=false \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=/home/runner/work/AeroSharp/AeroSharp/ \
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: /home/runner/work/AeroSharp/AeroSharp/coverage.net7.0.opencover.xml,/home/runner/work/AeroSharp/AeroSharp/coverage.net6.0.opencover.xml
          fail_ci_if_error: true
